components:
    parameters:
        id:
            in: path
            name: id
            required: true
            schema:
                $ref: '#/components/schemas/id'
        name:
            in: path
            name: name
            required: true
            schema:
                $ref: '#/components/schemas/name'
    schemas:
        CreateBody:
            properties:
                first_name:
                    type: string
                last_name:
                    type: string
            required:
                - first_name
            type: object
        CreateResponse:
            properties:
                fist_name:
                    type: string
                id:
                    maximum: 1.8446744073709552e+19
                    minimum: 0
                    type: integer
                last_name:
                    type: string
            required:
                - id
                - fist_name
            type: object
        GetResponse:
            properties:
                message:
                    type: string
            required:
                - message
            type: object
        Ret:
            items:
                properties:
                    embed:
                        properties:
                            key:
                                type: string
                            other_embed:
                                properties:
                                    key:
                                        type: string
                                    value:
                                        type: string
                                required:
                                    - key
                                    - value
                                type: object
                            others:
                                items:
                                    type: string
                                type: array
                            value:
                                type: string
                        required:
                            - key
                            - other_embed
                        type: object
                    map:
                        additionalProperties:
                            type: string
                        type: object
                    message:
                        type: string
                    other_map:
                        additionalProperties:
                            properties:
                                key:
                                    type: string
                                value:
                                    type: string
                            required:
                                - key
                                - value
                            type: object
                        type: object
                required:
                    - message
                    - embed
                type: object
            type: array
        httpGenericError:
            properties:
                id:
                    type: string
                message:
                    type: string
                status:
                    type: integer
            type: object
        id:
            maximum: 1.8446744073709552e+19
            minimum: 0
            type: integer
        name:
            type: string
    securitySchemes:
        Authorization:
            scheme: bearer
            type: http
        Basic:
            scheme: basic
            type: http
info:
    description: OpenAPI
    title: OpenAPI
    version: 0.0.1
openapi: 3.0.3
paths:
    /example:
        get:
            operationId: GET/example
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Ret'
                    description: OK
                "400":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        application/xml:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        multipart/form-data:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                    description: Bad Request
                "401":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        application/xml:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        multipart/form-data:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                    description: Unauthorized
                "404":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        application/xml:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        multipart/form-data:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                    description: Not Found
                "500":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        application/xml:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        multipart/form-data:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                    description: Internal Server Error
    /example/{id}:
        post:
            description: Create example
            operationId: createExample
            parameters:
                - $ref: '#/components/parameters/id'
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateBody'
            responses:
                "201":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateResponse'
                    description: OK
                "400":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        application/xml:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        multipart/form-data:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                    description: Bad Request
                "401":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        application/xml:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        multipart/form-data:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                    description: Unauthorized
                "404":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        application/xml:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        multipart/form-data:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                    description: Not Found
                "500":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        application/xml:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        multipart/form-data:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                    description: Internal Server Error
            security:
                - Authorization: []
            tags:
                - example
    /example/{name}:
        get:
            operationId: GET/example/:name
            parameters:
                - $ref: '#/components/parameters/name'
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetResponse'
                        application/xml:
                            schema:
                                $ref: '#/components/schemas/GetResponse'
                    description: OK
                "400":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        application/xml:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        multipart/form-data:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                    description: Bad Request
                "401":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        application/xml:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        multipart/form-data:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                    description: Unauthorized
                "404":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        application/xml:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        multipart/form-data:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                    description: Not Found
                "500":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        application/xml:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                        multipart/form-data:
                            schema:
                                $ref: '#/components/schemas/httpGenericError'
                    description: Internal Server Error
            security:
                - Basic: []
servers:
    - description: example server
      url: http://localhost:6001
