components:
    parameters:
        id:
            in: path
            name: id
            required: true
            schema:
                $ref: '#/components/schemas/id'
        name:
            in: path
            name: name
            required: true
            schema:
                $ref: '#/components/schemas/name'
    schemas:
        CreateBody:
            properties:
                first_name:
                    type: string
                last_name:
                    type: string
            required:
                - first_name
            type: object
        CreateResponse:
            properties:
                fist_name:
                    type: string
                id:
                    maximum: 1.8446744073709552e+19
                    minimum: 0
                    type: integer
                last_name:
                    type: string
            type: object
        GetResponse:
            properties:
                message:
                    type: string
            type: object
        id:
            type: string
        name:
            type: string
    securitySchemes:
        Authorization:
            scheme: bearer
            type: http
        Basic:
            scheme: basic
            type: http
info:
    description: OpenAPI
    title: OpenAPI
    version: 0.0.1
openapi: 3.0.3
paths:
    /example/{id}:
        post:
            description: Create example
            operationId: createExample
            parameters:
                - $ref: '#/components/parameters/id'
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateBody'
            responses:
                "201":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateResponse'
                    description: OK
                default:
                    description: ""
            security:
                - Authorization: []
            tags:
                - example
    /example/{name}:
        get:
            operationId: GET/example/:name
            parameters:
                - $ref: '#/components/parameters/name'
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetResponse'
                    description: OK
                default:
                    description: ""
            security:
                - Basic: []
servers:
    - description: example server
      url: http://localhost:3000
